### ISSUE TITLE
Object 'eps' not found with assoc 'etaslope'

### ISSUE THREAD

**Issue by jburos** [sambrilleman/rstanarm#19]
#### Summary:
I see: `Error: object 'eps' not found` when fitting a model with `assoc = c("etavalue", "etaslope")`

Specifically:

```r
> fit <- stan_jm(
+         ...
+         assoc = c("etavalue", "etaslope")
+     )
 Hide Traceback
 
 Rerun with Debug
 Error: object 'eps' not found 
2.
autoscale_prior(a_prior_stuff, a_mod_stuff, QR = QR, use_x = FALSE, 
    assoc = assoc) 
1.
stan_jm( ... )
```

#### RStanARM Version:
I am running off the master branch of `sambrilleman/rstanarm`: 

```r
devtools::install_github('sambrilleman/rstanarm', ref='master', args='--preclean', local=TRUE)
```

#### R Version:
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"

#### Operating System:
I've seen this on both my Macbook pro & on an ubuntu gcloud instance (Platform: x86_64-pc-linux-gnu (64-bit))

**Comment by sambrilleman** [comment]
Fix here: https://github.com/sambrilleman/rstanarm/pull/21
